version: '3.9'

services:
  db:
    image: postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: adam
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
